### ISSUE TITLE
Fix sifter slot and hole

### ISSUE THREAD

**Issue by eric-wieser** [eric-wieser/2.12-robot#29]
While we're at it, some small holes in the back to attach chicken wire to would be handy

And maybe reduce the guard height to 2 or 3 inches

**Comment by 14kirchm** [comment]
The sifter fell into pieces. We'll nee a new one pretty soon !

**Comment by 14kirchm** [comment]
Weak part

![sifter](https://cloud.githubusercontent.com/assets/15007187/11460502/62d12cfc-96bb-11e5-8e61-0d2fe1161f5c.jpg)

**Comment by 14kirchm** [comment]
3 pieces to repair 

![repari1](https://cloud.githubusercontent.com/assets/15007187/11460526/dfaf2832-96bb-11e5-9bad-ae99ffb3b8d5.jpeg)
![repari2](https://cloud.githubusercontent.com/assets/15007187/11460527/e4ba570c-96bb-11e5-8665-2996f521fe55.jpeg)

**Comment by reaganm** [comment]
I can lasercut the new and improved sifter tonight if I can get into MITERs
past midnight.  Otherwise we'll have to wait until tomorrow night.

**Comment by eric-wieser** [comment]
Did you ever commit this new and improved sifter?

**Comment by reaganm** [comment]
Yes, it should be the one that is in the repository.  The only thing I had
planned on changing was filleting the top corners.

**Comment by reaganm** [comment]
Just added some lasercutter files, but the solidworks files should be
unchanged

**Comment by eric-wieser** [comment]
Do we thing #49 is fixable with how this is cut, or is that going to have to be fixed another way?

**Comment by reaganm** [comment]
I think ideally we'd want something bendy that we can use as a guide ramp
or something (like paper or cardboard) that would not catch on the dump
truck as the sifter is being lifted, so probably not acrylic-- though I can
cut cardboard on the laser cutter also.

**Comment by eric-wieser** [comment]
Drilling some small mounting holes for cable-tying cardboard on might be a good use of laser-cutter

**Comment by eric-wieser** [comment]
"drilling"

**Comment by reaganm** [comment]
Okay, I can add some small mounting holes on the open side.

**Comment by reaganm** [comment]
fixed when new sifter was lasercut
