### ISSUE TITLE
Move CAD to hardware subfolder

### ISSUE THREAD

**Issue by eric-wieser** [eric-wieser/2.12-robot#39]
@premphy, @reaganm: In order to make this easy, the following needs to happen:

* You check in all your changes
* You close solidworks
* I move the folder, and commit
* You sync/pull, and can resume work

**Comment by reaganm** [comment]
I have committed/closed solidworks.

**Comment by premphy** [comment]
You can move the folder, Eric. I will then pull and commit my new parts into it
Thanks.


________________________________
Chandan Sharma Subedi
Department of Mechanical Engineering
Massachusetts Institute of Technology
premphy@mit.edu | 617-608-8694

________________________________

**Comment by eric-wieser** [comment]
Done

**Comment by premphy** [comment]
Great!


________________________________
Chandan Sharma Subedi
Department of Mechanical Engineering
Massachusetts Institute of Technology
premphy@mit.edu | 617-608-8694

________________________________
